import {
  PawPrint,
  HeartPulse,
  Sparkles,
  Egg,
  Activity,
  ArrowLeftRight,
  Syringe,
  Pill,
  FlaskConical,
  ShieldCheck,
  Home,
  CheckCircle2,
  ListTodo,
  Users,
  BellRing,
  Megaphone,
  Radio,
  CloudSun,
  History,
} from 'lucide-react'
import type { ModuleSection } from './model'

const ACC = {
  animals: 'var(--color-acc-animals)',
  animalsDeep: 'var(--color-acc-animals-deep)',
  animalsSoft: 'var(--color-acc-animals-soft)',
  medical: 'var(--color-acc-medical)',
  births: 'var(--color-acc-births)',
  eggs: 'var(--color-acc-eggs)',
  transfers: 'var(--color-acc-transfers)',
  approvals: 'var(--color-acc-approvals)',
  alerts: 'var(--color-acc-alerts)',
  weather: 'var(--color-acc-weather)',
  attendance: 'var(--color-acc-attendance)',
  neutral: '#c3ccc6',
}

export const site = {
  userName: 'Subhash',
  zooName: 'Jamnagar Wildlife Campus',
  weather: { tempC: 24, summary: 'Partly cloudy' },
}

export const sections: ModuleSection[] = [
  {
    id: 'animals',
    title: 'Animals',
    chip: 'Animals',
    icon: PawPrint,
    accent: ACC.animals,
    status: { tone: 'good', text: 'Healthy population' },
    hero: {
      value: 215432,
      label: 'Animals',
      delta: { text: '+324 this month', direction: 'up', positive: true },
      trend: [62, 63, 63, 64, 65, 65, 66, 68, 69, 70, 72, 74],
    },
    byRange: {
      today: { delta: { text: '+18 today', direction: 'up', positive: true } },
      week: { delta: { text: '+52 this week', direction: 'up', positive: true } },
    },
    split: {
      title: 'Sex distribution',
      segments: [
        { label: 'Male', value: '98,410', share: 0.457, color: ACC.animalsDeep },
        { label: 'Female', value: '104,270', share: 0.484, color: ACC.animalsSoft },
        { label: 'Unknown', value: '12,752', share: 0.059, color: ACC.neutral },
      ],
    },
    breakdown: {
      title: 'Species class',
      items: [
        { label: 'Birds', value: '98,450', share: 1 },
        { label: 'Fish', value: '41,320', share: 0.42 },
        { label: 'Reptiles', value: '31,240', share: 0.32 },
        { label: 'Mammals', value: '24,180', share: 0.25 },
        { label: 'Amphibians', value: '12,760', share: 0.13 },
        { label: 'Invertebrates', value: '7,482', share: 0.08 },
      ],
    },
    stats: {
      title: 'This month',
      items: [
        { label: 'Births', value: '324' },
        { label: 'Acquisitions', value: '86' },
        { label: 'Transfers', value: '112' },
        { label: 'Released', value: '38' },
        { label: 'Deaths', value: '23' },
        { label: 'Sites', value: '6' },
      ],
    },
    activity: {
      title: 'Recent movement',
      items: [
        { time: '10:24', text: 'Asiatic lion transferred to Enclosure B' },
        { time: '09:15', text: 'Two flamingo chicks added to aviary records' },
        { time: '08:02', text: 'Gharial released to wetland habitat' },
      ],
    },
    actions: ['Add animal', 'Search records'],
  },
  {
    id: 'health',
    title: 'Health & Medical',
    chip: 'Health',
    icon: HeartPulse,
    accent: ACC.medical,
    status: { tone: 'warn', text: 'Needs attention' },
    hero: {
      value: 123,
      label: 'Animals under medical care',
      delta: { text: '−9 vs last week', direction: 'down', positive: true },
      trend: [58, 61, 66, 64, 60, 57, 55, 56, 52, 50, 48, 46],
    },
    stats: {
      title: 'Care status',
      items: [
        { label: 'Hospitalised', value: '45' },
        { label: 'Critical', value: '8', accent: true },
        { label: 'Observation', value: '32' },
        { label: 'Isolation', value: '12' },
        { label: 'Recovery', value: '26' },
        { label: 'Admitted today', value: '9' },
        { label: 'Discharged today', value: '6' },
        { label: 'Active medication', value: '61' },
      ],
    },
    breakdown: {
      title: 'Top diagnoses',
      items: [
        { label: 'Respiratory infection', value: '28', share: 1 },
        { label: 'Parasitic load', value: '21', share: 0.75 },
        { label: 'Injury / trauma', value: '17', share: 0.61 },
        { label: 'Digestive disorder', value: '12', share: 0.43 },
      ],
    },
    activity: {
      title: 'Recent treatments',
      items: [
        { time: '11:20', text: 'Elephant calf — fluid therapy completed' },
        { time: '10:45', text: 'Leopard — wound dressing changed' },
        { time: '09:42', text: 'Rhino — antibiotic course started' },
      ],
    },
    actions: ['New case', 'Ward round'],
  },
  {
    id: 'births',
    title: 'Births',
    chip: 'Births',
    icon: Sparkles,
    accent: ACC.births,
    status: { tone: 'good', text: 'Strong breeding season' },
    hero: {
      value: 324,
      label: 'Births this month',
      delta: { text: '+12% vs last month', direction: 'up', positive: true },
      trend: [20, 24, 22, 28, 30, 27, 33, 36, 34, 38, 41, 45],
    },
    byRange: {
      today: { value: 5, label: 'Births today', delta: { text: '3 aviary · 2 mammal house', direction: 'flat', positive: true } },
      week: { value: 45, label: 'Births this week', delta: { text: '+8 vs previous week', direction: 'up', positive: true } },
    },
    breakdown: {
      title: 'By class',
      items: [
        { label: 'Birds', value: '201', share: 1 },
        { label: 'Mammals', value: '58', share: 0.29 },
        { label: 'Reptiles', value: '44', share: 0.22 },
        { label: 'Amphibians', value: '21', share: 0.1 },
      ],
    },
    activity: {
      title: 'Recent',
      items: [
        { time: '09:15', text: 'New hatch recorded — greater flamingo' },
        { time: 'Yesterday', text: 'Blackbuck fawn — mother and calf stable' },
      ],
    },
    actions: ['Record birth'],
  },
  {
    id: 'eggs',
    title: 'Eggs & Incubation',
    chip: 'Eggs',
    icon: Egg,
    accent: ACC.eggs,
    status: { tone: 'good', text: 'On schedule' },
    hero: {
      value: 45,
      label: 'Eggs collected this week',
      delta: { text: '21 under incubation', direction: 'flat', positive: true },
      trend: [12, 15, 11, 18, 16, 20, 22, 19, 24, 21, 26, 24],
    },
    stats: {
      title: 'Pipeline',
      items: [
        { label: 'Incubating', value: '21' },
        { label: 'Expected hatch (7d)', value: '7' },
        { label: 'Hatched this month', value: '12' },
        { label: 'Discarded', value: '4' },
      ],
    },
    meter: { label: 'Fertility rate', value: '78%', fraction: 0.78 },
    breakdown: {
      title: 'By species',
      items: [
        { label: 'Flamingo', value: '18', share: 1 },
        { label: 'Peafowl', value: '11', share: 0.61 },
        { label: 'Hornbill', value: '9', share: 0.5 },
        { label: 'Pheasant', value: '7', share: 0.39 },
      ],
    },
    activity: {
      title: 'Recent',
      items: [
        { time: '08:30', text: 'Clutch of 4 moved to incubator 3' },
        { time: 'Yesterday', text: 'Two hornbill eggs candled — viable' },
      ],
    },
    actions: ['Log collection'],
  },
  {
    id: 'mortality',
    title: 'Mortality',
    chip: 'Mortality',
    icon: Activity,
    accent: ACC.alerts,
    status: { tone: 'good', text: 'Below seasonal average' },
    hero: {
      value: 23,
      label: 'Deaths this month',
      delta: { text: '−18% vs last month', direction: 'down', positive: true },
      trend: [42, 38, 40, 35, 33, 30, 31, 28, 26, 27, 24, 23],
    },
    byRange: {
      today: { value: 2, label: 'Deaths in last 24 hours', delta: { text: 'both geriatric cases', direction: 'flat', positive: true } },
      week: { value: 8, label: 'Deaths this week', delta: { text: '−3 vs previous week', direction: 'down', positive: true } },
    },
    breakdown: {
      title: 'By cause',
      items: [
        { label: 'Age-related', value: '9', share: 1 },
        { label: 'Disease', value: '7', share: 0.78 },
        { label: 'Injury', value: '4', share: 0.44 },
        { label: 'Unknown', value: '3', share: 0.33 },
      ],
    },
    stats: {
      title: 'Casework',
      items: [
        { label: 'Postmortem pending', value: '3', accent: true },
        { label: 'Reports filed', value: '20' },
      ],
    },
    actions: ['Report mortality'],
  },
  {
    id: 'transfers',
    title: 'Transfers',
    chip: 'Transfers',
    icon: ArrowLeftRight,
    accent: ACC.transfers,
    status: { tone: 'neutral', text: '4 awaiting clearance' },
    hero: {
      value: 12,
      label: 'Active transfers',
      delta: { text: '5 incoming · 7 outgoing', direction: 'flat', positive: true },
      trend: [8, 10, 7, 12, 9, 11, 14, 10, 13, 12, 15, 12],
    },
    stats: {
      title: 'Status',
      items: [
        { label: 'Pending', value: '4' },
        { label: 'Completed (month)', value: '112' },
        { label: 'Internal', value: '9' },
        { label: 'External', value: '3' },
      ],
    },
    activity: {
      title: 'Movement timeline',
      items: [
        { time: '10:24', text: 'Asiatic lion → Enclosure B (internal)' },
        { time: '08:40', text: 'Two sarus cranes dispatched to Gir centre' },
        { time: 'Yesterday', text: 'Sloth bear arrival — quarantine started' },
      ],
    },
    actions: ['New transfer'],
  },
  {
    id: 'vaccination',
    title: 'Vaccination',
    icon: Syringe,
    accent: ACC.medical,
    status: { tone: 'warn', text: '3 overdue' },
    hero: {
      value: 17,
      label: 'Due this week',
      delta: { text: '128 completed this month', direction: 'flat', positive: true },
      trend: [30, 34, 28, 36, 40, 38, 42, 39, 44, 41, 45, 43],
    },
    meter: { label: 'Coverage', value: '92%', fraction: 0.92 },
    actions: ['Schedule drive'],
  },
  {
    id: 'deworming',
    title: 'Deworming',
    icon: Pill,
    accent: ACC.eggs,
    status: { tone: 'good', text: 'On schedule' },
    hero: {
      value: 34,
      label: 'Scheduled this week',
      delta: { text: '210 completed this month', direction: 'flat', positive: true },
      trend: [50, 48, 52, 55, 51, 54, 58, 56, 60, 57, 62, 59],
    },
    actions: ['View schedule'],
  },
  {
    id: 'lab',
    title: 'Lab Requests',
    icon: FlaskConical,
    accent: ACC.approvals,
    status: { tone: 'neutral', text: '14 in queue' },
    hero: {
      value: 14,
      label: 'Pending requests',
      delta: { text: '22 resulted today', direction: 'flat', positive: true },
      trend: [18, 16, 20, 17, 15, 19, 14, 16, 13, 15, 14, 14],
    },
    stats: {
      title: 'Queue',
      items: [
        { label: 'In progress', value: '9' },
        { label: 'Awaiting sample', value: '5' },
        { label: 'Urgent', value: '2', accent: true },
      ],
    },
    actions: ['New request'],
  },
  {
    id: 'welfare',
    title: 'Animal Welfare',
    icon: ShieldCheck,
    accent: ACC.animals,
    status: { tone: 'good', text: 'Above benchmark' },
    hero: {
      value: 4.6,
      format: 'score',
      label: 'Composite welfare score / 5',
      delta: { text: '+0.2 this quarter', direction: 'up', positive: true },
      trend: [78, 80, 79, 82, 84, 83, 85, 86, 88, 87, 90, 92],
    },
    stats: {
      title: 'Audits',
      items: [
        { label: 'Assessments due', value: '12' },
        { label: 'Flagged', value: '3', accent: true },
      ],
    },
    actions: ['Start assessment'],
  },
  {
    id: 'enclosures',
    title: 'Enclosure Assessments',
    icon: Home,
    accent: ACC.transfers,
    status: { tone: 'warn', text: '5 flagged' },
    hero: {
      value: 8,
      label: 'Assessments due',
      delta: { text: '132 passed this quarter', direction: 'flat', positive: true },
      trend: [12, 10, 14, 11, 9, 13, 10, 8, 11, 9, 10, 8],
    },
    meter: { label: 'Occupancy', value: '87%', fraction: 0.87 },
    actions: ['Inspect now'],
  },
  {
    id: 'approvals',
    title: 'Approvals',
    chip: 'Approvals',
    icon: CheckCircle2,
    accent: ACC.approvals,
    status: { tone: 'warn', text: '3 overdue' },
    hero: {
      value: 12,
      label: 'Pending approvals',
      delta: { text: 'avg turnaround 1.8 days', direction: 'flat', positive: true },
      trend: [18, 15, 17, 14, 16, 13, 15, 12, 14, 13, 12, 12],
    },
    breakdown: {
      title: 'By department',
      items: [
        { label: 'Veterinary', value: '5', share: 1 },
        { label: 'Finance', value: '4', share: 0.8 },
        { label: 'HR', value: '2', share: 0.4 },
        { label: 'Administration', value: '1', share: 0.2 },
      ],
    },
    activity: {
      title: 'Recent requests',
      items: [
        { time: '11:05', text: 'Medicine procurement — ₹48,000 (Finance)' },
        { time: '09:50', text: 'Night-shift roster change (HR)' },
        { time: '08:40', text: 'Lab report sign-off (Veterinary)' },
      ],
    },
    actions: ['Review queue', 'Quick approve'],
  },
  {
    id: 'tasks',
    title: 'Tasks',
    icon: ListTodo,
    accent: ACC.attendance,
    status: { tone: 'neutral', text: '9 due today' },
    hero: {
      value: 26,
      label: 'Open tasks',
      delta: { text: '41 completed this week', direction: 'flat', positive: true },
      trend: [30, 32, 28, 31, 27, 29, 26, 28, 25, 27, 26, 26],
    },
    meter: { label: 'Week completion', value: '61%', fraction: 0.61 },
    actions: ['My tasks'],
  },
  {
    id: 'attendance',
    title: 'Staff Attendance',
    icon: Users,
    accent: ACC.attendance,
    status: { tone: 'good', text: 'Full shift cover' },
    hero: {
      value: 94,
      format: 'percent',
      label: 'Staff present',
      delta: { text: '312 of 332 on duty', direction: 'flat', positive: true },
      trend: [90, 92, 91, 93, 92, 94, 93, 95, 94, 93, 95, 94],
    },
    stats: {
      title: 'Today',
      items: [
        { label: 'On duty', value: '312' },
        { label: 'On leave', value: '14' },
        { label: 'Absent', value: '6', accent: true },
      ],
    },
    actions: ['Roster'],
  },
  {
    id: 'alerts',
    title: 'Alerts',
    chip: 'Alerts',
    icon: BellRing,
    accent: ACC.alerts,
    status: { tone: 'critical', text: '1 critical' },
    hero: {
      value: 5,
      label: 'Active alerts',
      delta: { text: '3 warnings · 1 info', direction: 'flat', positive: false },
      trend: [8, 6, 7, 5, 6, 4, 5, 3, 4, 5, 4, 5],
    },
    activity: {
      title: 'Latest',
      items: [
        { time: '11:32', text: 'Critical — water quality, Reptile House' },
        { time: '10:12', text: 'Warning — humidity drift, Incubator 2' },
        { time: '09:03', text: 'Warning — gate sensor offline, North entry' },
      ],
    },
    actions: ['Acknowledge all'],
  },
  {
    id: 'announcements',
    title: 'Announcements',
    icon: Megaphone,
    accent: ACC.weather,
    status: { tone: 'neutral', text: '3 new' },
    hero: {
      value: 3,
      label: 'New announcements',
      delta: { text: 'this week', direction: 'flat', positive: true },
    },
    activity: {
      title: 'Latest',
      items: [
        { time: 'Today', text: 'Monsoon preparedness drill on 4 Aug' },
        { time: 'Yesterday', text: 'New enrichment protocol published' },
      ],
    },
    actions: ['Read all'],
  },
  {
    id: 'iot',
    title: 'IoT Devices',
    icon: Radio,
    accent: ACC.transfers,
    status: { tone: 'warn', text: '7 offline' },
    hero: {
      value: 248,
      label: 'Devices online',
      delta: { text: '99.2% uptime (30d)', direction: 'flat', positive: true },
      trend: [96, 97, 97, 98, 97, 98, 99, 98, 99, 99, 98, 99],
    },
    stats: {
      title: 'Fleet',
      items: [
        { label: 'Offline', value: '7', accent: true },
        { label: 'Low battery', value: '12' },
        { label: 'Total devices', value: '255' },
      ],
    },
    actions: ['Device map'],
  },
  {
    id: 'weather',
    title: 'Weather',
    chip: 'Weather',
    icon: CloudSun,
    accent: ACC.weather,
    status: { tone: 'neutral', text: 'Partly cloudy' },
    hero: {
      value: 24,
      format: 'degrees',
      label: 'Jamnagar — feels like 27°',
      delta: { text: 'high 31° · low 22°', direction: 'flat', positive: true },
      trend: [22, 22, 23, 24, 26, 28, 30, 31, 30, 28, 26, 24],
    },
    stats: {
      title: 'Conditions',
      items: [
        { label: 'Humidity', value: '68%' },
        { label: 'Wind', value: '12 km/h' },
        { label: 'UV index', value: '6' },
        { label: 'Rain chance', value: '20%' },
      ],
    },
  },
  {
    id: 'activity',
    title: 'Recent Activity',
    icon: History,
    accent: ACC.animals,
    status: { tone: 'neutral', text: 'Live feed' },
    hero: {
      value: 132,
      label: 'Events logged today',
      delta: { text: 'across 6 sites', direction: 'flat', positive: true },
    },
    activity: {
      title: 'Today',
      items: [
        { time: '11:20', text: 'Elephant calf — fluid therapy completed' },
        { time: '10:24', text: 'Lion transferred to Enclosure B' },
        { time: '09:42', text: 'Elephant vaccination completed' },
        { time: '09:15', text: 'New hatch recorded' },
        { time: '08:40', text: 'Lab report approved' },
      ],
    },
    actions: ['Full log'],
  },
]
