/**
 * Bundles the builder into a runnable Figma plugin — the path that creates real
 * auto-layout frames without needing any MCP write tool.
 *
 *   node tools/figma/build-plugin.mjs   →  tools/figma/plugin/{manifest.json,code.js}
 *
 * In Figma desktop: Plugins → Development → Import plugin from manifest…
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { HERE } from './paths.mjs'

const DIR = resolve(HERE, 'plugin')
mkdirSync(DIR, { recursive: true })

const prelude = readFileSync(resolve(HERE, 'prelude.js'), 'utf8')
const homeLib = readFileSync(resolve(HERE, 'home.js'), 'utf8')
const data = JSON.parse(readFileSync(resolve(HERE, 'antz-data.json'), 'utf8'))
const icons = JSON.parse(readFileSync(resolve(HERE, 'antz-icons.json'), 'utf8'))

writeFileSync(resolve(DIR, 'manifest.json'), JSON.stringify({
  name: 'ANTZ Command Centre → Screens',
  id: 'antz-command-centre-screens',
  api: '1.0.0',
  main: 'code.js',
  editorType: ['figma'],
  // Required since 2023 — a missing networkAccess fails at plugin-environment load,
  // before any code runs. The builder makes no network calls.
  networkAccess: { allowedDomains: ['none'] },
}, null, 2))

const PAGE_NAME = 'ANTZ — Command Centre'
const STRIDE = 390 + 80

const code = `/* ANTZ Command Centre → Figma
 * Generated by tools/figma/build-plugin.mjs from the live app source.
 * Builds 15 screens (home + 14 module detail pages) as 390x844 frames with
 * real auto-layout, editable text and vector charts.
 */
const ICONS = ${JSON.stringify(icons)}
const HOME = ${JSON.stringify(data.home)}
const PAGES = ${JSON.stringify(data.pages)}
const PAGE_NAME = ${JSON.stringify(PAGE_NAME)}
const STRIDE = ${STRIDE}

${prelude}
${homeLib}

async function main() {
  // Build on whatever page is open, so the screens land where you're looking.
  // Frames are placed to the right of any existing content, never on top of it.
  const page = figma.currentPage
  await initFonts()

  let startX = 0
  for (let k = 0; k < page.children.length; k++) {
    const n = page.children[k]
    if (typeof n.x === 'number' && typeof n.width === 'number') {
      startX = Math.max(startX, n.x + n.width + 120)
    }
  }

  const made = []
  const frames = []
  const built = buildHome(HOME, startX, 0, 'Good Afternoon')
  page.appendChild(built.frame)
  built.frame.x = startX
  built.frame.y = 0
  frames.push(built.frame)
  made.push({ name: built.frame.name, id: built.frame.id, content: Math.round(built.contentHeight) })

  for (let i = 0; i < PAGES.length; i++) {
    const p = PAGES[i]
    const others = PAGES.filter(function (q) { return q.slug !== p.slug })
      .map(function (q) { return { slug: q.slug, title: q.title } })
    const x = startX + STRIDE * (i + 1)
    const r = buildDetailPage(p, others, x, 0)
    page.appendChild(r.frame)
    r.frame.x = x
    r.frame.y = 0
    frames.push(r.frame)
    made.push({ name: r.frame.name, id: r.frame.id, content: Math.round(r.contentHeight) })
  }

  // Hold the nodes directly — no getNodeById lookup, which the async document
  // access modes disallow.
  page.selection = frames
  figma.viewport.scrollAndZoomIntoView(frames)
  return made
}

main()
  .then(function (made) {
    figma.closePlugin('Built ' + made.length + ' screens on this page')
  })
  .catch(function (e) {
    figma.closePlugin('Failed: ' + (e && e.message ? e.message : String(e)))
  })
`

writeFileSync(resolve(DIR, 'code.js'), code)
console.log(`plugin/code.js   ${(code.length / 1024).toFixed(0)} KB`)
console.log(`plugin/manifest.json`)
console.log(`\nFigma desktop → Plugins → Development → Import plugin from manifest…`)
console.log(`  ${resolve(DIR, 'manifest.json')}`)
