/**
 * Assembles paste-ready `use_figma` payloads from the prelude + builders + data.
 * Each emitted file is a complete, self-contained script for one Figma frame.
 *
 *   node tools/figma/build-scripts.mjs
 *
 *   out/00-setup.js        page + variable collection  (run first)
 *   out/01-home.js         the home screen
 *   out/02..15-<slug>.js   the 14 module detail pages
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs'
import { resolve } from 'node:path'
import { HERE, OUT } from './paths.mjs'

mkdirSync(OUT, { recursive: true })

const prelude = readFileSync(resolve(HERE, 'prelude.js'), 'utf8')
const homeLib = readFileSync(resolve(HERE, 'home.js'), 'utf8')
const data = JSON.parse(readFileSync(resolve(HERE, 'antz-data.json'), 'utf8'))
const allIcons = JSON.parse(readFileSync(resolve(HERE, 'antz-icons.json'), 'utf8'))

const PAGE_NAME = 'ANTZ — Command Centre (from code)'
/** Target file — Antz Command Center. Scripts refuse to write anywhere else. */
const FILE_KEY = 'WvxVp4VXLXD5JwMFlYehjR'
const GAP = 80
const FRAME_W = 390
const STRIDE = FRAME_W + GAP

/** Only ship the icons a given script actually draws. */
const iconSubset = (names) => {
  const out = {}
  for (const n of names) if (allIcons[n]) out[n] = allIcons[n]
  return out
}
const CHROME_ICONS = ['ChevronRight', 'ChevronDown', 'Bell', 'X']

const header = (title) => `/* ANTZ → Figma · ${title}
   Generated by tools/figma/build-scripts.mjs from the live app source.
   Pass as the \`code\` arg of use_figma with skillNames: "figma-use". */\n`

const pageBootstrap = `
const PAGE_NAME = ${JSON.stringify(PAGE_NAME)}
const FILE_KEY = ${JSON.stringify(FILE_KEY)}
// Wrong file open in Figma → refuse, rather than scattering frames somewhere else.
if (typeof figma.fileKey === 'string' && figma.fileKey && figma.fileKey !== FILE_KEY) {
  throw new Error('Wrong Figma file open: ' + figma.fileKey + ' — expected ' + FILE_KEY + ' (Antz Command Center)')
}
let target = figma.root.children.find((p) => p.name === PAGE_NAME)
if (!target) throw new Error('Run 00-setup.js first — page not found: ' + PAGE_NAME)
await figma.setCurrentPageAsync(target)
`

/* ── 00 setup: page + colour variables ───────────────────────────────────── */
const TOKENS = {
  'ground/base': '#e7f0ea',
  'surface/card-home': '#fbfaf7',
  'surface/card-detail': '#ffffff',
  'ink/primary': '#1c1a16',
  'ink/secondary': '#3d3a34',
  'ink/muted': '#6d6860',
  'ink/faint': '#9b958b',
  'ink/chapter': '#5f6b62',
  'brand/green': '#034739',
  'delta/positive': '#37bd69',
  'delta/negative': '#fa6140',
  'tone/good': '#1e7a44',
  'tone/warn': '#b45309',
  'tone/bad': '#dc2626',
  'line/grid': '#f0efec',
  'line/track': '#f2f1ed',
  'line/divider': '#f4f3ef',
}

writeFileSync(resolve(OUT, '00-setup.js'), `${header('setup — page + variables')}
const PAGE_NAME = ${JSON.stringify(PAGE_NAME)}
const FILE_KEY = ${JSON.stringify(FILE_KEY)}
const TOKENS = ${JSON.stringify(TOKENS, null, 2)}

// Confirm we're in Antz Command Center before creating anything.
const openKey = typeof figma.fileKey === 'string' ? figma.fileKey : null
if (openKey && openKey !== FILE_KEY) {
  throw new Error('Wrong Figma file open: ' + openKey + ' — expected ' + FILE_KEY + ' (Antz Command Center)')
}

const hex = (h) => {
  const n = parseInt(h.replace('#', ''), 16)
  return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255 }
}

let page = figma.root.children.find((p) => p.name === PAGE_NAME)
if (!page) { page = figma.createPage(); page.name = PAGE_NAME }
await figma.setCurrentPageAsync(page)

const collections = await figma.variables.getLocalVariableCollectionsAsync()
let col = collections.find((c) => c.name === 'ANTZ')
if (!col) col = figma.variables.createVariableCollection('ANTZ')
const existing = {}
for (const id of col.variableIds) {
  const v = await figma.variables.getVariableByIdAsync(id)
  if (v) existing[v.name] = v
}
const mode = col.modes[0].modeId
const made = []
for (const [name, value] of Object.entries(TOKENS)) {
  let v = existing[name]
  if (!v) {
    v = figma.variables.createVariable(name, col, 'COLOR')
    v.scopes = ['FRAME_FILL', 'SHAPE_FILL', 'TEXT_FILL', 'STROKE_COLOR']
    made.push(name)
  }
  v.setValueForMode(mode, hex(value))
}

const fonts = await figma.listAvailableFontsAsync()
const have = new Set(fonts.map((f) => \`\${f.fontName.family}|\${f.fontName.style}\`))
const check = ['Inter|Regular', 'Inter|Medium', 'Inter|Semi Bold', 'Inter|SemiBold', 'Inter|Bold', 'Space Grotesk|Bold']

return {
  pageId: page.id,
  pageName: page.name,
  collectionId: col.id,
  variablesCreated: made,
  variableCount: col.variableIds.length,
  fontsPresent: check.filter((c) => have.has(c)),
  fontsMissing: check.filter((c) => !have.has(c)),
}
`)

/* ── 01 home ─────────────────────────────────────────────────────────────── */
const homeIcons = new Set(CHROME_ICONS)
const H = data.home
for (const c of [...H.mainPair, ...H.dailyUpdates, ...H.moduleCards, ...H.moreModules, H.welfare]) homeIcons.add(c.icon)

writeFileSync(resolve(OUT, '01-home.js'), `${header('Home screen')}
const ICONS = ${JSON.stringify(iconSubset([...homeIcons]))}
const DATA = ${JSON.stringify(H)}
${prelude}
${homeLib}
${pageBootstrap}
await initFonts()
const startX = target.children.reduce((m, n) => (typeof n.x === 'number' && typeof n.width === 'number' ? Math.max(m, n.x + n.width + 120) : m), 0)
const built = buildHome(DATA, startX, 0, 'Good Afternoon')
target.appendChild(built.frame)
built.frame.x = startX; built.frame.y = 0
return { createdNodeIds: [built.frame.id], name: built.frame.name, size: [built.frame.width, built.frame.height], contentHeight: Math.round(built.contentHeight), startX: startX }
`)

/* ── 02..15 detail pages ─────────────────────────────────────────────────── */
data.pages.forEach((page, i) => {
  const others = data.pages.filter((p) => p.slug !== page.slug).map((p) => ({ slug: p.slug, title: p.title }))
  const names = new Set([...CHROME_ICONS, page.icon])
  const n = String(i + 2).padStart(2, '0')
  writeFileSync(resolve(OUT, `${n}-${page.slug}.js`), `${header(`Detail — ${page.title}`)}
const ICONS = ${JSON.stringify(iconSubset([...names]))}
const PAGE = ${JSON.stringify(page)}
const OTHERS = ${JSON.stringify(others)}
${prelude}
${pageBootstrap}
await initFonts()
const home = target.children.find((n) => n.name && n.name.indexOf('Home —') === 0)
const baseX = home ? home.x : 0
const x = baseX + ${STRIDE * (i + 1)}
const r = buildDetailPage(PAGE, OTHERS, x, 0)
target.appendChild(r.frame)
r.frame.x = x; r.frame.y = 0
return { createdNodeIds: [r.frame.id], name: r.frame.name, size: [r.frame.width, r.frame.height], contentHeight: Math.round(r.contentHeight), sections: PAGE.sections.length }
`)
})

/* ── report ──────────────────────────────────────────────────────────────── */
const files = readdirSync(OUT).filter((f) => f.endsWith('.js')).sort()
console.log(files.map((f) => {
  const kb = (statSync(resolve(OUT, f)).size / 1024).toFixed(1)
  return `${f.padEnd(20)} ${kb.padStart(7)} KB`
}).join('\n'))
console.log(`\n${files.length} scripts · frames at x = 0, ${STRIDE}, ${STRIDE * 2}, … (stride ${STRIDE})`)
